// <auto-generated />
using System;
using ClinicManagementSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260119130823_AllDataBase")]
    partial class AllDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicManagementSystem.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("DeletedByType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentName = "Internal Medicine"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentName = "Surgery"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentName = "Pediatrics"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentName = "Orthopedics"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentName = "Cardiology"
                        });
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.DoctorAssist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("AssistAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AssistName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AssistTel1")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AssistTel2")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("CanLogin")
                        .HasColumnType("bit");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginPassword")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoginUsername")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("LoginUsername")
                        .IsUnique()
                        .HasFilter("[LoginUsername] IS NOT NULL");

                    b.ToTable("DoctorAssists");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.DoctorInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("CanLogin")
                        .HasColumnType("bit");

                    b.Property<string>("DoctorAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DoctorCivilId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DoctorDetails")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("DoctorPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("DoctorTel1")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DoctorTel2")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DoctorTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginPassword")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoginUsername")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SpecialistId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoginUsername")
                        .IsUnique()
                        .HasFilter("[LoginUsername] IS NOT NULL");

                    b.HasIndex("SpecialistId");

                    b.HasIndex("UserId");

                    b.ToTable("DoctorInfos");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.DoctorSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubscriptionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorSubscriptions");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("PatientAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PatientCivilID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PatientTel1")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PatientTel2")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.PatientDiagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DiagnosisDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnosisDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DiagnosisFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientDiagnoses");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageAssistants")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageDepartments")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageDiagnoses")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageDoctors")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManagePatients")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageSpecialists")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageUsers")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewReports")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ViewAllPatients")
                        .HasColumnType("bit");

                    b.Property<bool>("ViewOwnPatientsOnly")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CanManageAssistants = true,
                            CanManageDepartments = true,
                            CanManageDiagnoses = true,
                            CanManageDoctors = true,
                            CanManagePatients = true,
                            CanManageSpecialists = true,
                            CanManageUsers = true,
                            CanViewReports = true,
                            Description = "Full system access",
                            RoleName = "Super Admin",
                            ViewAllPatients = true,
                            ViewOwnPatientsOnly = false
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CanManageAssistants = true,
                            CanManageDepartments = true,
                            CanManageDiagnoses = false,
                            CanManageDoctors = true,
                            CanManagePatients = true,
                            CanManageSpecialists = true,
                            CanManageUsers = false,
                            CanViewReports = true,
                            Description = "Administrative access",
                            RoleName = "Admin",
                            ViewAllPatients = true,
                            ViewOwnPatientsOnly = false
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CanManageAssistants = false,
                            CanManageDepartments = false,
                            CanManageDiagnoses = true,
                            CanManageDoctors = false,
                            CanManagePatients = true,
                            CanManageSpecialists = false,
                            CanManageUsers = false,
                            CanViewReports = false,
                            Description = "Doctor access - own patients only",
                            RoleName = "Doctor",
                            ViewAllPatients = false,
                            ViewOwnPatientsOnly = true
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CanManageAssistants = false,
                            CanManageDepartments = false,
                            CanManageDiagnoses = false,
                            CanManageDoctors = false,
                            CanManagePatients = true,
                            CanManageSpecialists = false,
                            CanManageUsers = false,
                            CanViewReports = false,
                            Description = "Doctor assistant - limited access",
                            RoleName = "Assistant",
                            ViewAllPatients = false,
                            ViewOwnPatientsOnly = true
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CanManageAssistants = false,
                            CanManageDepartments = false,
                            CanManageDiagnoses = false,
                            CanManageDoctors = false,
                            CanManagePatients = true,
                            CanManageSpecialists = false,
                            CanManageUsers = false,
                            CanViewReports = false,
                            Description = "Front desk - patient management only",
                            RoleName = "Receptionist",
                            ViewAllPatients = true,
                            ViewOwnPatientsOnly = false
                        });
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.Specialist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SpecialistName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Specialists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Description = "Heart and cardiovascular diseases",
                            SpecialistName = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Description = "General surgical procedures",
                            SpecialistName = "General Surgery"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Description = "Children's health care",
                            SpecialistName = "Pediatrics"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            Description = "Bone and joint surgery",
                            SpecialistName = "Orthopedic Surgery"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            Description = "Heart and blood vessel diseases",
                            SpecialistName = "Cardiovascular"
                        });
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserFullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserTel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("UserInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            JobTitle = "Administrator",
                            RoleId = 1,
                            UserFullName = "System Administrator",
                            UserName = "admin",
                            UserPassword = "Admin@123"
                        });
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.Appointment", b =>
                {
                    b.HasOne("ClinicManagementSystem.Models.DoctorInfo", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManagementSystem.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.DoctorAssist", b =>
                {
                    b.HasOne("ClinicManagementSystem.Models.DoctorInfo", "Doctor")
                        .WithMany("DoctorAssists")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.DoctorInfo", b =>
                {
                    b.HasOne("ClinicManagementSystem.Models.Specialist", "Specialist")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicManagementSystem.Models.UserInfo", "User")
                        .WithMany("Doctors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Specialist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.DoctorSubscription", b =>
                {
                    b.HasOne("ClinicManagementSystem.Models.DoctorInfo", "Doctor")
                        .WithMany("Subscriptions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.Patient", b =>
                {
                    b.HasOne("ClinicManagementSystem.Models.DoctorInfo", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.PatientDiagnosis", b =>
                {
                    b.HasOne("ClinicManagementSystem.Models.DoctorInfo", "Doctor")
                        .WithMany("PatientDiagnoses")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicManagementSystem.Models.Patient", "Patient")
                        .WithMany("PatientDiagnoses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.Specialist", b =>
                {
                    b.HasOne("ClinicManagementSystem.Models.Department", "Department")
                        .WithMany("Specialists")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.UserInfo", b =>
                {
                    b.HasOne("ClinicManagementSystem.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.Department", b =>
                {
                    b.Navigation("Specialists");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.DoctorInfo", b =>
                {
                    b.Navigation("DoctorAssists");

                    b.Navigation("PatientDiagnoses");

                    b.Navigation("Patients");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.Patient", b =>
                {
                    b.Navigation("PatientDiagnoses");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.Specialist", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("ClinicManagementSystem.Models.UserInfo", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
